
export const PolerasHombre = [
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1078016-1200-1200?v=638574601338070000&width=1200&height=1200&aspect=true",
        "name": "Nike Club",
        "description": "Esta playera de ajuste clásico es relajada en todo el cuerpo para facilitar el uso en capas. La ligera tela de punto brinda sensación de suavidad.",
        "category": "Ropa",
        "color": "Verde",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0, //randomize
        // table also contains create at column
    },
    {"imageURL": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4aaeca766de54e8da99463ab93c5910a_9366/Polera_sin_Mangas_Own_The_Run_Blanco_IK7435_21_model.jpg",
        "name": "Polera sin mangas own the run",
        "description": "Una prenda esencial para tus carreras diarias, esta polera sin mangas adidas mantiene tu cuerpo seco de principio a fin gracias a la tecnología AEROREADY. Concéntrate en tu mejor marca personal y no en tu top gracias al diseño que se mueve contigo. Los detalles reflectantes te hacen más visible.",
        "category": "Ropa",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/50db1b32c549467c980300be1e3318e5_9366/Polera_Capa_Base_Manga_Larga_Terrex_Xperior_Merino_150_Negro_HZ8559_21_model.jpg",
        "name": "Polera capa base manga larga terrex xperior merino 150",
        "description": "Ponte esta polera manga larga de lana Merino de adidas Terrex y sal a explorar. Diseñada para que puedas pasar más tiempo afuera en terrenos variados, la mezcla de lana Merino y lyocell brinda un tacto suave a la vez que regula la temperatura corporal. Ofreciendo comodidad en diversas actividades y temperaturas. Las costuras planas evitan la irritación de la piel para que puedas avanzar con tranquilidad en la ruta elegida. El dobladillo posterior alargado brinda mayor protección contra el mal tiempo.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/59eba54b610b4c8497215a6af68ae9c7_9366/Polera_Shmoofoil_Big_Bad_City_Negro_IZ4859_21_model.jpg",
        "name": "Polera shmoofoil big bad city",
        "description": "Con estampados personalizados creados por Mark Gonzales, la polera Shmoofoil Big Bad City combina la estética distintiva de Mark con una polera clásica y suave de algodón manga corta para el skateboarding. El algodón de este producto fue obtenido a través de Better Cotton. El algodón Better Cotton se obtiene a través de un modelo de cadena de custodia llamado balance de masas. Esto significa que Better Cotton no es físicamente rastreable a nivel de productos finales. Descubre más aquí: https://bettercotton.org/who-we-are/our-logo/",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/03c0876df7aa4e00a10eb150aa9fb730_9366/Polera_Essentials_Logo_Grande_Tejido_Jersey_Azul_IX0138_21_model.jpg",
        "name": "Polera essentials logo grande tejido jersey",
        "description": "Sin importar si lo estás luciendo luego de entrenar o preparándote para comenzar el día, esta polera básica de adidas es justo lo que necesitas. Hecha para ofrecer comodidad y un estilo descomplicado, el logo adidas Badge of Sport brilla en el frente para destacar tu amor por adidas. Combina con cualquier outfit de tu armario y su clásica energía deportiva combina a la perfección con cualquier look.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1069216-1200-1200?v=638570099078200000&width=1200&height=1200&aspect=true",
        "name": "Polera Jordan",
        "description": "Rinde homenaje a uno de los mejores con total comodidad. Confeccionada con algodón de densidad media, esta Polera clásica ofrece suavidad y una ligera caída. Eso es lo que llamamos una combinación ganadora.",
        "category": "Ropa",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/997349-1200-1200?v=638488864580030000&width=1200&height=1200&aspect=true",
        "name": "Sportswear premium essentials",
        "description": "La playera de manga larga Nike Sportswear tiene un ajuste holgado para brindar un look relajado y cómodo. Su tela de algodón orgánico de alta densidad se siente gruesa y suave. El logotipo sutil de Futura en la parte delantera central ofrece un look Nike exclusivo, al tiempo que el cuello asegura un ajuste impecable y cómodo. Este producto está confeccionado con al menos un 75% de fibras de algodón orgánico.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1031154-1200-1200?v=638548410081330000&width=1200&height=1200&aspect=true",
        "name": "Sportswear premium essentials",
        "description": "La playera Nike Sportswear Premium essentials ofrece un ajuste suelto para brindar un look desenfadado y cómodo. Su tela de algodón orgánico de alta densidad se siente gruesa y suave. Este producto está confeccionado con al menos un 75% de fibras de algodón orgánico.",
        "category": "Ropa",
        "color": "Marrón",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/998579-1200-1200?v=638488888072770000&width=1200&height=1200&aspect=true",
        "name": "Nike club fleece",
        "description": "Polo de manga larga de tejido Fleece para hombre. Con una mezcla de diseños, este polo Nike Club Fleece aporta un acabado perfeccionado con su cuello con botones y apliques cosidos. El amplio bolsillo de canguro y el ajuste relajado ayudan a mantener la comodidad vayas donde vayas",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       },
       {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1044876-1200-1200?v=638550192943030000&width=1200&height=1200&aspect=true",
        "name": "Air jordan wordmark 85",
        "description": "Te presentamos un clásico mejorado. El algodón de alta densidad aporta a esta playera sencilla un ajuste estructurado que puedes llevar cualquier día de la semana.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Polera",
        "price": 0,
        // table also contains create at column
       }
]

export const CamisasHombre = [
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3249186-1200-1595?v=638578932656930000&width=1200&height=1595&aspect=true",
        "name": "Camisa brood",
        "description": "Camisa casual en calce slim con largo untucked para usar fuera del pantalón. Con botones escondidos en el cuello para mantener su posición. Esta prenda tiene un lavado especial extra suavizante para un mejor tacto y sensación en el cuerpo. En disenos funiculares estampados fobre fondo azul jeanseado. Complementa tu look con nuestra línea de pantalónes casuales.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3258925-1200-1595?v=638578939492870000&width=1200&height=1595&aspect=true",
        "name": "Camisa blas",
        "description": "Camisa Casual manga larga en calce slim fit con largo untucked, para usar fuera del pantalón. Cuello con botones encondidos. En una fantasía de paisley en celeste y café sobre fondo blanco , es perfecta para tus fines de semana.",
        "category": "Ropa",
        "color": "Beige",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3251229-1200-1595?v=638578934138630000&width=1200&height=1595&aspect=true",    
        "name": "Camisa non iron",
        "description": "Camisa en calce Slim de nuestra línea Travel.Desarrollada en algodón en un dobby color azul, cuello clásico, puño simple y tapeta frontal. Esta prenda ha sido fabricada bajo altos estándares de calidad con tecnología Non Iron que mantiene su apariencia de planchado por más tiempo al activarse con la temperatura de tu cuerpo",
        "category": "Ropa",
        "color": "",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3249206-1200-1595?v=638578932666300000&width=1200&height=1595&aspect=true",
        "name": "Camisa formal executive",
        "description": "Camisa formal en calce Slim de nuestra línea Executive para el uso constante. Con mezcla de algodón y poliéster la hacen una prenda resistente al uso. Cuello Francés, puno en dobby en color rosado.",
        "category": "Ropa",
        "color": "",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3249488-1200-1595?v=638578932887500000&width=1200&height=1595&aspect=true",
        "name": "Camisa formal europea",
        "description": "Camisa formal de nuestra línea Italiana en custom fit. Fabricada en algodón italiano de color blanco/celeste microdiseño. Cuello italiano y puño simple con costuras especiales. Esta prenda es única y diseñada en Europa para otorgar la mejor calidad y estilo.",
        "category": "Ropa",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3199711-1200-1595?v=638568337643400000&width=1200&height=1595&aspect=true",
        "name": "Camisa formal hombre microdiseño",
        "description": "Camisa de hombre formal, en calce slim, con cuello italiano, elaborado con algodón y elastano para mayor comodidad y movimiento. microdiseño falso liso en tono celeste.",
        "category": "Ropa",
        "color": "Celeste",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3166819-1200-1595?v=638568309540200000&width=1200&height=1595&aspect=true",
        "name": "Camisa formal",
        "description": "Camisa formal en calce SLIM, de nuestra línea DYNAMIC. En una mezcla de algodón con elastano, para otorgar una mayor libertad de movimiento. Microdiseno simple y sin tapeta frontal. Esta prenda ha sido fabricada bajo altos estándares de calidad, exclusivamente para TRIAL.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3155791-1200-1595?v=638568296685000000&width=1200&height=1595&aspect=true",
        "name": "Camisa hombre formal",
        "description": "Camisa formal en calce SLIM, de nuestra línea DYNAMIC. En una mezcla de algodón con elastano, para otorgar una mayor libertad de movimiento. Microdiseno simple y sin tapeta frontal. Esta prenda ha sido fabricada bajo altos estándares de calidad, exclusivamente para TRIAL.",
        "category": "Ropa",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Camisa",
        "price": 0,
        // table also contains create at column
    }, 
]

export const ChaquetasHombre = [
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3006986-1200-1595?v=638496065109870000&width=1200&height=1595&aspect=true",
        "name": "Chaqueta hombre casual algodón liso",
        "description": "Chaqueta casual de hombre en calce slim, bolsillo parche en el pecho con forro que simula pañuelo, bolsillos parche en parte posterior. Nuestra chaqueta Captain M está elaborada con tela 100% algodón con un tejido único.",
        "category": "Ropa",
        "color": "Azul Marino",
        "gender": "Hombre",
        "garment_type": "Chaqueta",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3268378-1200-1595?v=638598798972000000&width=1200&height=1595&aspect=true",
        "name": "Chaqueta hombre casual mezcla lana lino cuadros",
        "description": "Destaca con nuestra chaqueta Cosimo para hombre, en una elegante mezcla de lana y lino con patrón de cuadros en azul. Su diseño slim proporciona una silueta ajustada y moderna, ideal para un look casual sofisticado. El tejido mezcla asegura comodidad y frescura, mientras que el patrón de cuadros añade un toque distintivo y contemporáneo.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Chaqueta",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3274991-1200-1595?v=638605525854470000&width=1200&height=1595&aspect=true",
        "name": "Chaqueta denim hombre casual algodón liso",
        "description": "La chaqueta Denim Tifón para hombre en verde combina un estilo casual con un calce slim que acentúa la figura. Confeccionada en algodón liso de alta calidad, ofrece comodidad y durabilidad en un diseño moderno.",
        "category": "Ropa",
        "color": "Verde",
        "gender": "Hombre",
        "garment_type": "Chaqueta",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/2999088-1200-1595?v=638496060788300000&width=1200&height=1595&aspect=true",
        "name": "Chaqueta casual hombre",
        "description": "Chaqueta de hombre casual en color camel, calce slim, cuello camisero y cierre frontal invisible, bolsillos laterales en costura, forro interior al tono reversible.",
        "category": "Ropa",
        "color": "Camel",
        "gender": "Hombre",
        "garment_type": "Chaqueta",
        "price": 0,
        // table also contains create at column
    },
]

export const PantalonesHombre = [
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1069170-1200-1200?v=638570098298730000&width=1200&height=1200&aspect=true",
        "name": "Nike tech",
        "description": "Estos pants de entrenamiento clásicos se renuevan con un estilo funcional para el aire libre. Están confeccionados con un suave tejido Woven de nylon arrugado que cuenta con repelencia al agua y protección UV para ofrecer comodidad, elegancia y funcionalidad.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1078193-1200-1200?v=638574603869170000&width=1200&height=1200&aspect=true",
        "name": "Nike sportswear",
        "description": "Para celebrar que el breaking formará parte del mayor escenario deportivo, Nike se asoció con el fundador del hip hop y legendario grafitero neoyorquino FUTURA para renovar los pants Nike Windrunner. El nylon duradero de la capa exterior se combina con un forro de malla absorbente de sudor para crear una prenda cómoda que favorece el movimiento.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1078036-1200-1200?v=638574601623800000&width=1200&height=1200&aspect=true",
        "name": "Nike primary",
        "description": "Estos pants Primary absorbentes de sudor están hechos con un tejido Knit de densidad media diseñado para el movimiento. Cuentan con un ajuste clásico que se estrecha a lo largo de la pierna y con costuras planas para evitar el roce.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1077747-1200-1200?v=638574597074370000&width=1200&height=1200&aspect=true",
        "name": "Jordan MVP",
        "description": "¿Todo listo para el gran momento? Creemos que podrías usar estos pants MVP. Confeccionados con un tejido Woven suave y ligero, cuentan con ribetes reflectantes para ofrecer un look llamativo.",
        "category": "Ropa",
        "color": "Verde",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1077780-1200-1200?v=638574597617130000&width=1200&height=1200&aspect=true",
        "name": "Nike SB Kearny",
        "description": "Estos pants ligeros absorbentes del sudor están diseñados para el movimiento y la comodidad. Con seis bolsillos tendrás muchos lugares para guardar de forma segura los artículos básicos con o sin la patineta. Las cintas del dobladillo te permiten ceñirlos a la altura del tobillo o dejarlos abiertos para sentir el flujo de aire.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1069195-1200-1200?v=638570098692600000&width=1200&height=1200&aspect=true",
        "name": "Giannis",
        "description": "El escudo de estos joggers Standard Issue rinde homenaje a los mayores seguidores de Giannis: su familia. Diseñados con un ajuste clásico, están confeccionados con un suave tejido Fleece que absorbe el sudor.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1069144-1200-1200?v=638570097854700000&width=1200&height=1200&aspect=true",
        "name": "Nike Icon",
        "description": "Ligeros y transpirables, estos pants de básquetbol Icon tienen una cubierta de tejido Woven absorbente de sudor y un forro interior de malla para mantener la frescura. Su ajuste holgado les da un estilo de ropa de calentamiento retro que se usa fácilmente sobre los shorts.",
        "category": "Ropa",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Pantalon",
        "price": 0,
        // table also contains create at column
    },
]

export const JeansHombre = [
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3089263-1200-1595?v=638496104819930000&width=1200&height=1595&aspect=true",
        "name": "Jeans hombre casual slim fit nebula",
        "description": "Jeans color azul marino de calce skinny, suaves focalizados para dar dimensión a la prenda, con tela suavizada priorizando la comodidad.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Jeans",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3044659-1200-1595?v=638496083490630000&width=1200&height=1595&aspect=true",
        "name": "Jeans hombre casual slim fit metropoli",
        "description": "Jeans color azul medio de calce slim, 5 bolsillos con suave focalizados para crear movimiento en la prenda, con tela suavizada para mayor",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Jeans",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3253811-1200-1595?v=638578936043030000&width=1200&height=1595&aspect=true",
        "name": "Jeans nomad",
        "description": "Jeans Calce skinny para un hombre Trial moderno. 5 bolsillos en color azul marino con lavados especiales para un tacto suavizado. Cierre metalico con bloqueo automatico.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Jeans",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3250496-1200-1595?v=638578933628930000&width=1200&height=1595&aspect=true",
        "name": "Jeans skinny nazario",
        "description": "Jeans Trial en calce Skinny color azul marino, tiro medio. Con botones y aplicaciones metalicos. Una prenda moderna con lavado suavizado para mejor sensación al tacto.",
        "category": "Ropa",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Jeans",
        "price": 0,
        // table also contains create at column
    },
]

export const BotasHombre = [
    {"imageURL": "https://columbiacl.vtexassets.com/arquivos/ids/362446-1600-auto?v=638479256932500000&width=1600&height=auto&aspect=true",
        "name": "Botín Hombre Transverse Hike Wateproof Negro",
        "description": "Un resistente zapato de senderismo impermeable que ofrece excelente tracción y comodidad.",
        "category": "Calzado",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Botin",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://columbiacl.vtexassets.com/arquivos/ids/321411-1600-auto?v=638240114256100000&width=1600&height=auto&aspect=true",
        "name": "Botín Hombre Newton Ridge Plus II Waterproof",
        "description": "Un resistente zapato de senderismo impermeable que ofrece excelente tracción y comodidad.",
        "category": "Calzado",
        "color": "Cafe",
        "gender": "Hombre",
        "garment_type": "Botin",
        "price": 0,
        // table also contains create at column
    },  
    {"imageURL": "https://columbiacl.vtexassets.com/arquivos/ids/361404-1600-auto?v=638479250868200000&width=1600&height=auto&aspect=true",
        "name": "Botín Hombre Newton Ridge Plus II Waterproof",
        "description": "Un resistente zapato de senderismo impermeable que ofrece excelente tracción y comodidad.",
        "category": "Calzado",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Botin",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://columbiacl.vtexassets.com/arquivos/ids/362247-1600-auto?v=638479255752070000&width=1600&height=auto&aspect=true",
        "name": "Botín Hombre Newton Ridge II Suede Waterproof",
        "description": "Una bota de senderismo duradera y liviana en gamuza, diseñada para brindar comodidad, protección y estilo.",
        "category": "Calzado",
        "color": "Cafe",
        "gender": "Hombre",
        "garment_type": "Botin",
        "price": 0,
        // table also contains create at column
    },
]

export const ZapatillasHombre = [
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/160788-1200-1200?v=637654399741130000&width=1200&height=1200&aspect=true",
        "name": "Nike Air Force 1 '07",
        "description": "El fulgor vive en el Nike Air Force 1 ’07, el modelo original de básquetbol que da un toque novedoso a las características más recordadas: revestimientos con costuras duraderas, acabados impecables y la cantidad perfecta de destellos para que brilles.",
        "category": "Calzado",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Zapatilla",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/723384-1200-1200?v=638241048856100000&width=1200&height=1200&aspect=true",
        "name": "Air Jordan 1 Low",
        "description": "¿Quieres comodidad todo el día, todos los días? La tenemos. El AJ1 Low cuenta con todos los looks del calzado original de básquetbol, con menos peso y un perfil elegante. Además, van con cualquier atuendo: solo amarra las agujetas y ponte en marcha.",
        "category": "Calzado",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Zapatilla",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1058621-1200-1200?v=638557103476970000&width=1200&height=1200&aspect=true",
        "name": "Nike P-6000",
        "description": "Los P-6000 son una combinación de tenis Pegasus anteriores, llevan las carreras de principios de los años 2000 a la era moderna. Con malla ventilada y líneas deportivas, son la combinación perfecta de looks llamativos y comodidad transpirable.",
        "category": "Calzado",
        "color": "Blanco",
        "gender": "Hombre",
        "garment_type": "Zapatilla",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://nikeclprod.vtexassets.com/arquivos/ids/1031569-1200-1200?v=638548415690930000&width=1200&height=1200&aspect=true",
        "name": "JORDAN MVP",
        "description": "Quizá no inventamos el remix, pero al pensar en el material que teníamos para probar, hicimos una versión superfácil. Tomamos elementos de los AJ6, 7 y 8, para convertirlos en unos Zapatillas completamente nuevos que rinden homenaje a la primera ronda de 3 campeonatos victoriosos de MJ. Con detalles de cuero, tela y nobuk, estos Zapatillas rinden homenaje a un legado y al mismo tiempo te alientan a construir el tuyo.",
        "category": "Calzado",
        "color": "Rojo",
        "gender": "Hombre",
        "garment_type": "Zapatilla",
        "price": 0,
        // table also contains create at column
    },
]

export const ZapatosHombre = [
    {"imageURL": "https://cdn.guante.cl/27015-large_default/zapato-guante-colorado-negro-0035362-1614781.webp",
        "name": "Zapato colorado",
        "description": "Descubre la combinación perfecta de tecnología y estilo con el zapato Colorado de cuero negro. Su tecnología G-WALK te proporciona la comodidad que necesitas para cada paso que des y en toda ocasión. Poseen una planta G-GRIP otorgando mayor sujeción y estabilidad en diferentes superficies. Ideal para el profesional moderno, este zapato es una inversión en versatilidad y sofisticación.",
        "category": "Calzado",
        "color": "Negro",
        "gender": "Hombre",
        "garment_type": "Zapato",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://cdn.guante.cl/28808-large_default/zapato-guante-prince-marino-0035546-1652492.webp",
        "name": "Zapato prince",
        "description": "Descubre la combinación perfecta de tecnología y estilo con el zapato Prince de cuero negro. Su tecnología G-WALK te proporciona la comodidad que necesitas para cada paso que des y en toda ocasión. Poseen una planta G-GRIP otorgando mayor sujeción y estabilidad en diferentes superficies. Ideal para el profesional moderno, este zapato es una inversión en versatilidad y sofisticación.",
        "category": "Calzado",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Zapato",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://cdn.guante.cl/26640-large_default/zapato-guante-pulso-nantes-marino-0034817-1181014.webp",
        "name": "Zapato nantes",
        "description": "El zapato NANTES de cuero color marino, te ofrece la versatilidad que buscas. Su diseño contemporáneo te permite expresar tu estilo en cualquier entorno. Gracias a su tecnología G-Walk con plantilla Bac-control, te proporciona una protección antibacterial efectiva, ayudando a eliminar el 99,9% de las bacterias que producen el mal olor. Camina con confianza y frescura durante todo el día.",
        "category": "Calzado",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Zapato",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://cdn.guante.cl/27523-large_default/zapato-guante-president-suela-president-chocolate-0035436-1418821.webp",
        "name": "Zapato president",
        "description": "Nuestro zapato Suela President de color chocolate, son desarrollados con cosido Goodyear Welt, que es uno de los métodos artesanales más antiguos. Consiste en una doble costura, la primera une el cuero del zapato a la vira y a la planta, la segunda consiste en una costura que une la vira a la suela. Entregando una resistencia y durabilidad inigualables. Se aplica una pasta de corcho en la parte central del zapato que funciona como aislante, además de adquirir la forma de la planta ajustándose a la pisada.",
        "category": "Calzado",
        "color": "Cafe",
        "gender": "Hombre",
        "garment_type": "Zapato",
        "price": 0,
        // table also contains create at column
    },
]

export const CinturonesHombre = [
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/2994218-1200-1595?v=638496058362500000&width=1200&height=1595&aspect=true",
        "name": "Cinturón formal liso",
        "description": "Cinturón básico Trial en color café , De nuestra línea de accesorios de manufactura Italiana. Hebilla metálica, 3,5 cm de ancho.",
        "category": "Accesorio",
        "color": "Cafe",
        "gender": "Hombre",
        "garment_type": "Cinturon",
        "price": 0,
        // table also contains create at column
    },
]

export const CorbataHombre = [
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3113185-1200-1595?v=638496122066200000&width=1200&height=1595&aspect=true",
        "name": "Corbata formal luxury seda",
        "description": "Corbata de hombre de la línea Luxury con microdiseño en tono azul marino, desarrollada en 100% seda. Ancho 7,5cm",
        "category": "Accesorio",
        "color": "Azul",
        "gender": "Hombre",
        "garment_type": "Corbata",
        "price": 0,
        // table also contains create at column
    },
    {"imageURL": "https://trialcl.vtexassets.com/arquivos/ids/3274656-1200-1595?v=638602789915730000&width=1200&height=1595&aspect=true",
        "name": "Corbata hombre formal seda travel",
        "description": "Composición 100% seda",
        "category": "Accesorio",
        "color": "Gris",
        "gender": "Hombre",
        "garment_type": "Corbata",
        "price": 0,
        // table also contains create at column
    }
]

/*
{"imageURL": "",
"name": "",
"description": "",
"category": "",
"color": "",
"gender": "",
"garment_type": "",
"price": 0,
// table also contains create at column
}
*/