# Generated by Django 3.2.25 on 2024-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
