# Generated by Django 5.1.1 on 2024-09-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_app', '0002_alter_joke_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ropa', 'Ropa'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio')], default='ropa', max_length=20)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5, null=True)),
                ('shoe_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('color', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('garment_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Joke',
        ),
    ]
